slug: mgc
name: MGC Icon System Pro - Carefully crafted icon solution for you
description: MGC Icon System Pro - Carefully crafted icon solution for you bookmarked for icons/svg resources.
category: Icons/SVG
parentCategory: design
subcategory: icons-svg
stars: 0
watchers: 0
addedDaysAgo: 0
license: Bookmark
lastCommit: Imported May 20, 2026
lastRelease: Bookmark
version: ""
platforms:
  - Web
deployment:
  - Cloud
website: https://mgc.mingcute.com/?aff=Z2vd4
docs: https://mgc.mingcute.com/?aff=Z2vd4
sourceCode: ""
icon: mgc
verified: false
featured: false
tags:
  - bookmark
  - design
  - icons-svg
  - icons
  - svg
atGlance: MGC Icon System Pro - Carefully crafted icon solution for you
fullDescription: >-
  MGC Icon System Pro - Carefully crafted icon solution for you was imported from the browser
  bookmark folder "Bookmarks bar > Design > ICONS/SVG".
