slug: designspells
name: Design Spells - Design details that feel like magic
description: Design Spells - Design details that feel like magic bookmarked for inspiration resources.
category: Inspiration
parentCategory: design
subcategory: inspiration
stars: 0
watchers: 0
addedDaysAgo: 0
license: Bookmark
lastCommit: Imported May 20, 2026
lastRelease: Bookmark
version: ""
platforms:
  - Web
deployment:
  - Cloud
website: https://www.designspells.com/
docs: https://www.designspells.com/
sourceCode: ""
icon: designspells
verified: false
featured: false
tags:
  - bookmark
  - design
  - inspiration
atGlance: Design Spells - Design details that feel like magic
fullDescription: >-
  Design Spells - Design details that feel like magic was imported from the browser bookmark folder
  "Bookmarks bar > Design > Insipiration".
