slug: tremor
name: Tremor - Copy-and-Paste Tailwind CSS UI Components for Charts and Dashboards
description: >-
  Tremor - Copy-and-Paste Tailwind CSS UI Components for Charts and Dashboards bookmarked for ui
  library resources.
category: UI Library
parentCategory: ui-libraries
subcategory: null
stars: 0
watchers: 0
addedDaysAgo: 0
license: Bookmark
lastCommit: Imported May 20, 2026
lastRelease: Bookmark
version: ""
platforms:
  - Web
deployment:
  - Cloud
website: https://tremor.so/
docs: https://tremor.so/
sourceCode: ""
icon: tremor
verified: false
featured: false
tags:
  - bookmark
  - ui-libraries
  - ui
  - library
atGlance: Tremor - Copy-and-Paste Tailwind CSS UI Components for Charts and Dashboards
fullDescription: >-
  Tremor - Copy-and-Paste Tailwind CSS UI Components for Charts and Dashboards was imported from the
  browser bookmark folder "Bookmarks bar > CMPNTS".
